account/urls.py
from django.urls import path
from .views import account_registration

app_name = "account"

urlpatterns = [
    path('account/registration/', account_registration, name="registration")
]

main/urls.py
from django.urls import path
from .views import MainIndex, MainShow, MainFilm, Mfilm, Maintech, MainPost, main_delete_post, main_view

app_name = "main"

urlpatterns = [
    path('', MainIndex, name="index"),
    path('Tvshows', MainShow, name="show"),
    path('film', MainFilm, name="film"),
    path('technology', Maintech, name='tech'),
    path('more-films', Mfilm, name="mfilm"),
    path('add-content', MainPost, name="content"),
    path('delete-post/<int:id>/', main_delete_post, name='delete-post'),
    path('view/<int:id>/', main_view, name='view')
]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('account/', include('account.urls'))
)

account/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from web.mixins import TranslateMixin


class Post(TranslateMixin, models.Model):
    translate_attributes = ['subject', 'content']

    subject_uz = models.CharField(max_length=100, verbose_name=_("Sarlavha (uz)"))
    subject_ru = models.CharField(max_length=100, verbose_name=_("Sarlavha (ru)"))
    content_uz = models.TextField(verbose_name=_("Content (uz)"))
    content_ru = models.TextField(verbose_name=_("Content (ru)"))
    image = models.ImageField()
    read = models.IntegerField(default=0)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


class RegistrationForm(forms.ModelForm):
    confirm = forms.CharField(label=_("Parol takroran"), widget=forms.PasswordInput)

    def clean_confirm(self):
        if self.cleaned_data['confirm'] != self.cleaned_data['password']:
            raise ValidationError

        return self.cleaned_data['confirm']

    class Meta:
        model = User
        fields = ['username', 'last_name', 'first_name', 'email', 'password']
        labels = {
            'username': _("Login"),
            'last_name': _("Familiya"),
            'first_name': _("Ismingiz"),
            'email': _("E-mail"),
            'password': _("Parol")
        }

        widgets = {
            'password': forms.PasswordInput
        }

account/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .forms import RegistrationForm
from django.utils.translation import gettext_lazy as _


def account_registration(request):
    page_title = _("Ro'yhatdan o'tish")
    request.button_title = page_title
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()

            return redirect('main:index')

    return render(request, "account/registration.html", {

        'form': form
    })


# Create your views here.

main/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Post
from .form import PostForm
from django.contrib import messages
from django.utils.translation import gettext_lazy as _


def MainIndex(request):
    sarlavha = _("Bosh sahifa")
    return render(request, "index.html", context={
        "page_title": sarlavha,
        "objects_list": Post.objects.all()
    })


def Maintech(request):
    sarlavha = _("Sci-Fi")
    return render(request, "tech.html", context={
        "page_title": sarlavha
    })


def MainShow(request):
    sarlavha = _("Tv Showlar")
    return render(request, "show.html", context={
        "page_title": sarlavha
    })


def Mfilm(request):
    sarlavha = _("Filmlar")
    return render(request, "mfilm.html", context={
        "page_title": sarlavha
    })


def MainReg(request):
    sarlavha = _("Ro'yhatdan o'tish")
    return render(request, "account/registration.html", context={
        "page_title": sarlavha
    })


def MainFilm(request):
    sarlavha = "Film"
    return render(request, "film.html", context={
        "page_title": sarlavha
    })


def MainPost(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()

            messages.success(request, _("Muvaffaqiyatli qo'shildi!"))

            return redirect('main:index')

    return render(request, 'main/add.html', {
        'form': form,
        "page_title": _("Maqola qo'shish")
    })


def main_delete_post(request, id):
    Post.objects.filter(id=id).delete()

    messages.success(request, _("Maqola o'chirildi!"))
    return redirect('main:index')


def main_view(request, id):
    post = Post.objects.get(id=id)

    request.breadcrumb = [
        post.subject
    ]
    return render(request, 'main/view.html', {
        'post': post
    })

templates/film.html
{% extends "layouts/base.html" %}
{% load static %}
{% block content %}
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'img/001.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/002.jpg' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/003.jpg' %}" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="thumbrow">
        <a href="{% url 'main:mfilm' %}" class="thumbrow list-header clickable">Trailer<span>For more films</span></a>
    </div>
{% endblock %}

templates/index.html
{% extends "layouts/base.html" %}
{% load static i18n %}
{% block content %}

    <div class="row">
        {% for item in objects_list %}
            <div class="col-lg-4 mb-3 align-items-stretch">
                <div class="card h-100">
                    {% if item.image %}
                        <img src="{{ item.image.url }}" class="card-img-top" alt="...">
                    {% else %}
                        <img src="{% static 'img/no.jpeg' %} }" class="card-img-top" alt="...">
                    {% endif %}
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ item.subject }}</h5>
                        <p class="card-text">{{ item.content }}</p>
                        <div class="mt-auto">
                            <div class="d-flex">
                                <a href="{% url 'main:view' item.id %}" class="btn btn-primary btn-sm">{% translate "Davomi" %}</a>
                                <a class="ms-auto btn btn-danger btn-sm"
                                   href="{% url 'main:delete-post' item.id %}">{% translate "O'chirish" %}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/layouts/base.html
{% load static i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page_title }}</title>
    <link rel="icon" href="{% static 'img/Film.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index' %}">
        <img
    src="https://media.unreel.me/prod/popcornflix/general/0e3dfcc3-5a76-40b0-8167-86476da80204" alt="" class="p-icon"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'main:film' %}">{% translate "Filmlar" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:show' %}">{% translate "Tv Showlar" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:tech' %}">{% translate "Sci-Fi" %}</a>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:content' %}">{% translate "Maqola qo'shish" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:registration' %}">{% translate "Ro'yhatdan o'tish" %}</a>
        </li>
          <li class="nav-item dropdown">
              <a href="#" data-bs-toggle="dropdown" class="dropdown-toggle btn btn-secondary">
                  {{ LANGUAGE_CODE }}
              </a>
              <div class="dropdown-menu">
                  {% for l in LANGUAGES %}
                      <a href="/{{ l.0 }}/" class="dropdown-item">{{ l.1 }}</a>
                  {% endfor %}
              </div>
          </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% if request.breadcrumb %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item f-bread"><a href="{% url 'main:index' %}">{% translate "Bosh sahifa" %}</a></li>
      {% for item in request.breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">{{ item }}</li>
    {% endfor %}
  </ol>
</nav>

{% endif %}

{% block content %}

{% endblock %}
<script src="{% static "/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

templates/layouts/form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters i18n %}
{% block content %}

<div class="row mt-md-3 p-md-5">
<div class="col-lg-6 offset-lg-3">
    <div class="card">
        <div class="card-header">{{ page_title }}</div>
        <div class="card-body">
            <form method="post" action="{% block form_url %}{% endblock %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-secondary">{% if request.button_title %}{{ request.button_title }}{% else %}{% translate "Qo'shish" %}{% endif %}</button>
        </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/main/add.html
{%  extends 'layouts/form.html' %}

{% block form_url %}{% url 'main:content' %}{% endblock %}

templates/main/view.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h1>{{ post.subject }}</h1>
    <div>
    {{ post.content }}
    </div>
{% endblock %}

templates/mfilm.html
{% extends 'layouts/base.html' %}


{% block content %}
<div style="background-color: red; font-size: 100px">
<h1>EMPTY WINDOW</h1>
</div>
{% endblock %}

templates/show.html
{% extends 'layouts/base.html' %}


{% block content %}


<div class="header">
    <h1>You haven't subscribtion</h1>
    <p>Subscribe any channel!</p>
</div>
{% endblock %}

templates/tech.html
 extends "layouts/base.html" %}
{% load static %}
{% block content %}
<div class="video">

    
</div>
{% endblock %}